"""PDFMasry API — secure edition (patched 2026-07-30).

Fixes CRITICAL vulnerability where downloads were addressed by the original
filename, letting anyone with a guessable name pull another user's file.

Every convert endpoint now:
  * stores files in <uploads>/<job_uuid>/  (per-job isolation)
  * returns a signed one-time download URL: /api/download/<job_id>/<token>
  * token = HMAC(secret, "<job_id>.<expiry>") with 1h TTL
  * uses the ORIGINAL filename only in Content-Disposition (RFC 5987)
  * emits Cache-Control: private, no-store on downloads
  * deletes the whole job dir after 1 hour via background task

Endpoints kept identical to the frontend's calls:
  POST /api/{tool}     → 200 {"status":"success","download_url":"/api/download/..."}
  GET  /api/download/{job_id}/{token}   → file with proper headers
"""
from __future__ import annotations

import asyncio
import hashlib
import hmac
import os
import re
import secrets
import shutil
import subprocess
import time
import unicodedata
import uuid
from urllib.parse import quote

from fastapi import (
    BackgroundTasks,
    FastAPI,
    File,
    Form,
    HTTPException,
    UploadFile,
)
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse

# --- استدعاء مكتبات أدوبي الحديثة (V4) ---
from adobe.pdfservices.operation.auth.service_principal_credentials import ServicePrincipalCredentials
from adobe.pdfservices.operation.pdf_services import PDFServices
from adobe.pdfservices.operation.pdf_services_media_type import PDFServicesMediaType
from adobe.pdfservices.operation.pdfjobs.jobs.export_pdf_job import ExportPDFJob
from adobe.pdfservices.operation.pdfjobs.params.export_pdf.export_pdf_params import ExportPDFParams
from adobe.pdfservices.operation.pdfjobs.params.export_pdf.export_pdf_target_format import ExportPDFTargetFormat
from adobe.pdfservices.operation.pdfjobs.result.export_pdf_result import ExportPDFResult

app = FastAPI(title="PDFMasry API Complete", version="5.0-secure")

# إعدادات الأمان (CORS) لحماية الباندويث الخاص بك
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "https://pdfmasry.com",
        "https://www.pdfmasry.com",
        "https://taupe-rugelach-921837.netlify.app",
        "https://pdfmasry-staging.netlify.app",
        "http://localhost:4321",
        "http://localhost:4322",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
    expose_headers=["Content-Disposition"],
)

UPLOAD_DIR = "./temp_files"
os.makedirs(UPLOAD_DIR, exist_ok=True)

# Secret used to sign download tokens. Set DOWNLOAD_SECRET on Railway.
# A missing secret still boots the server (falls back to a random per-boot
# value) — but tokens generated by one boot cannot be verified by another.
DOWNLOAD_SECRET = os.environ.get("DOWNLOAD_SECRET") or secrets.token_urlsafe(32)
DOWNLOAD_TOKEN_TTL_SECONDS = 60 * 60  # 1 hour
JOB_TTL_SECONDS = 60 * 60             # cleanup after 1 hour

# ---------------------------------------------------------
# Security helpers — UUID job dirs, signed tokens, sanitized names
# ---------------------------------------------------------

def _new_job_id() -> str:
    """32 hex chars, 128 bits of entropy — unguessable."""
    return uuid.uuid4().hex


def _job_dir(job_id: str) -> str:
    return os.path.join(UPLOAD_DIR, job_id)


def _sign(payload: str) -> str:
    return hmac.new(
        DOWNLOAD_SECRET.encode("utf-8"),
        payload.encode("utf-8"),
        hashlib.sha256,
    ).hexdigest()


def _make_token(job_id: str) -> str:
    expiry = int(time.time()) + DOWNLOAD_TOKEN_TTL_SECONDS
    sig = _sign(f"{job_id}.{expiry}")
    return f"{expiry}.{sig}"


def _verify_token(job_id: str, token: str) -> bool:
    try:
        expiry_str, sig = token.split(".", 1)
        expiry = int(expiry_str)
    except (ValueError, AttributeError):
        return False
    if time.time() > expiry:
        return False
    expected = _sign(f"{job_id}.{expiry}")
    return hmac.compare_digest(sig, expected)


def _sanitize_filename(name: str) -> str:
    """Safe display filename for Content-Disposition. Storage uses UUID."""
    name = os.path.basename(name or "file")
    name = re.sub(r"[\x00-\x1f\x7f/\\:*?\"<>|]+", "_", name)
    name = unicodedata.normalize("NFC", name).strip(" .")
    if not name:
        name = "file"
    return name[:120]


def _content_disposition(download_name: str) -> str:
    ascii_fallback = re.sub(r"[^A-Za-z0-9._-]+", "_", download_name) or "file"
    quoted = quote(download_name, safe="")
    return f'attachment; filename="{ascii_fallback}"; filename*=UTF-8\'\'{quoted}'


async def _save_upload_to_job(file: UploadFile) -> tuple[str, str, str]:
    """Create a fresh job dir, save the upload inside it as input.bin.
    Returns (job_id, job_dir, sanitized_original_name).
    """
    job_id = _new_job_id()
    jdir = _job_dir(job_id)
    os.makedirs(jdir, exist_ok=True)
    input_path = os.path.join(jdir, "input.bin")
    with open(input_path, "wb") as buffer:
        shutil.copyfileobj(file.file, buffer)
    return job_id, jdir, _sanitize_filename(file.filename or "file")


def _make_response(job_id: str, output_path: str, download_name: str, media_type: str) -> dict:
    """Move the produced file to <job_dir>/output.bin (canonical name),
    write meta so download endpoint knows the display name + type.
    """
    jdir = _job_dir(job_id)
    canonical = os.path.join(jdir, "output.bin")
    if os.path.abspath(output_path) != os.path.abspath(canonical):
        shutil.move(output_path, canonical)
    with open(os.path.join(jdir, "meta.txt"), "w", encoding="utf-8") as f:
        f.write(f"{media_type}\n{download_name}\n")
    return {
        "status": "success",
        "download_url": f"/api/download/{job_id}/{_make_token(job_id)}",
        "expires_in": DOWNLOAD_TOKEN_TTL_SECONDS,
    }


async def _delete_job_after_delay(job_id: str, delay_seconds: int = JOB_TTL_SECONDS):
    await asyncio.sleep(delay_seconds)
    jdir = _job_dir(job_id)
    if os.path.exists(jdir):
        shutil.rmtree(jdir, ignore_errors=True)

# ---------------------------------------------------------
# 1. المحرك الأساسي لأدوبي (Adobe V4) للتحويل العربي الدقيق
# ---------------------------------------------------------
def process_pdf_adobe_v4(input_path: str, output_path: str, target_format):
    client_id = os.getenv("ADOBE_CLIENT_ID")
    client_secret = os.getenv("ADOBE_CLIENT_SECRET")

    if not client_id or not client_secret:
        raise Exception("مفاتيح أدوبي غير موجودة في بيئة Railway")

    credentials = ServicePrincipalCredentials(client_id=client_id, client_secret=client_secret)
    pdf_services = PDFServices(credentials=credentials)

    with open(input_path, 'rb') as f:
        input_stream = f.read()
    input_asset = pdf_services.upload(input_stream=input_stream, mime_type=PDFServicesMediaType.PDF)

    export_pdf_params = ExportPDFParams(target_format=target_format)
    export_pdf_job = ExportPDFJob(input_asset=input_asset, export_pdf_params=export_pdf_params)

    location = pdf_services.submit(export_pdf_job)
    pdf_services_response = pdf_services.get_job_result(location, ExportPDFResult)

    result_asset = pdf_services_response.get_result().get_asset()
    stream_asset = pdf_services.get_content(result_asset)

    with open(output_path, "wb") as output_file:
        output_file.write(stream_asset.get_input_stream())

# ---------------------------------------------------------
# 2. Health + secure download
# ---------------------------------------------------------
@app.get("/")
def health_check():
    return {"status": "PDFMasry API is running with ALL Server Tools!", "version": app.version}


@app.get("/health")
def health():
    return {"status": "ok"}


@app.get("/api/download/{job_id}/{token}")
def download_file(job_id: str, token: str):
    # Only accept hex uuid.hex form to prevent path traversal via job_id
    if not re.fullmatch(r"[a-f0-9]{32}", job_id):
        raise HTTPException(status_code=404, detail="Not found")
    if not _verify_token(job_id, token):
        raise HTTPException(status_code=403, detail="Invalid or expired link")

    jdir = _job_dir(job_id)
    output = os.path.join(jdir, "output.bin")
    meta_path = os.path.join(jdir, "meta.txt")
    if not os.path.isfile(output) or not os.path.isfile(meta_path):
        raise HTTPException(status_code=404, detail="File not found or already deleted")

    with open(meta_path, "r", encoding="utf-8") as f:
        lines = f.read().splitlines()
    media_type = lines[0] if lines else "application/octet-stream"
    download_name = lines[1] if len(lines) > 1 else "download"

    response = FileResponse(output, media_type=media_type)
    response.headers["Content-Disposition"] = _content_disposition(download_name)
    response.headers["Cache-Control"] = "private, no-store"
    response.headers["Pragma"] = "no-cache"
    response.headers["X-Content-Type-Options"] = "nosniff"
    response.headers["Referrer-Policy"] = "no-referrer"
    return response

# ---------------------------------------------------------
# 3. مسارات أدوبي (للغة العربية)
# ---------------------------------------------------------
@app.post("/api/pdf-to-word")
async def convert_pdf_to_word(background_tasks: BackgroundTasks, file: UploadFile = File(...)):
    job_id, jdir, orig = await _save_upload_to_job(file)
    input_path = os.path.join(jdir, "input.bin")
    output_path = os.path.join(jdir, "converted.docx")
    try:
        process_pdf_adobe_v4(input_path, output_path, ExportPDFTargetFormat.DOCX)
        base = os.path.splitext(orig)[0] or "document"
        response_data = _make_response(
            job_id,
            output_path,
            f"{base}.docx",
            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        )
        background_tasks.add_task(_delete_job_after_delay, job_id)
        return response_data
    except Exception as e:
        background_tasks.add_task(_delete_job_after_delay, job_id, delay_seconds=5)
        raise HTTPException(status_code=500, detail=f"حدث خطأ: {str(e)}")


@app.post("/api/pdf-to-excel")
async def convert_pdf_to_excel(background_tasks: BackgroundTasks, file: UploadFile = File(...)):
    job_id, jdir, orig = await _save_upload_to_job(file)
    input_path = os.path.join(jdir, "input.bin")
    output_path = os.path.join(jdir, "converted.xlsx")
    try:
        process_pdf_adobe_v4(input_path, output_path, ExportPDFTargetFormat.XLSX)
        base = os.path.splitext(orig)[0] or "document"
        response_data = _make_response(
            job_id,
            output_path,
            f"{base}.xlsx",
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        )
        background_tasks.add_task(_delete_job_after_delay, job_id)
        return response_data
    except Exception as e:
        background_tasks.add_task(_delete_job_after_delay, job_id, delay_seconds=5)
        raise HTTPException(status_code=500, detail=f"حدث خطأ: {str(e)}")

# ---------------------------------------------------------
# 4. مسارات الأدوات المجانية (Ghostscript, qpdf, LibreOffice, Poppler)
# ---------------------------------------------------------
@app.post("/api/compress")
async def compress_pdf(background_tasks: BackgroundTasks, file: UploadFile = File(...)):
    job_id, jdir, orig = await _save_upload_to_job(file)
    input_path = os.path.join(jdir, "input.bin")
    output_path = os.path.join(jdir, "compressed.pdf")
    try:
        cmd = ["gs", "-sDEVICE=pdfwrite", "-dCompatibilityLevel=1.4",
               "-dPDFSETTINGS=/screen", "-dNOPAUSE", "-dQUIET", "-dBATCH",
               f"-sOutputFile={output_path}", input_path]
        subprocess.run(cmd, check=True, capture_output=True)
        response_data = _make_response(job_id, output_path, f"compressed_{orig}", "application/pdf")
        background_tasks.add_task(_delete_job_after_delay, job_id)
        return response_data
    except Exception:
        background_tasks.add_task(_delete_job_after_delay, job_id, delay_seconds=5)
        raise HTTPException(status_code=500, detail="فشل ضغط الملف")


@app.post("/api/protect")
async def protect_pdf(background_tasks: BackgroundTasks, file: UploadFile = File(...), password: str = Form("pdfmasry")):
    job_id, jdir, orig = await _save_upload_to_job(file)
    input_path = os.path.join(jdir, "input.bin")
    output_path = os.path.join(jdir, "protected.pdf")
    try:
        cmd = ["qpdf", "--encrypt", password, password, "256", "--", input_path, output_path]
        subprocess.run(cmd, check=True, capture_output=True)
        response_data = _make_response(job_id, output_path, f"protected_{orig}", "application/pdf")
        background_tasks.add_task(_delete_job_after_delay, job_id)
        return response_data
    except Exception:
        background_tasks.add_task(_delete_job_after_delay, job_id, delay_seconds=5)
        raise HTTPException(status_code=500, detail="فشلت حماية الملف")


@app.post("/api/unlock")
async def unlock_pdf(background_tasks: BackgroundTasks, file: UploadFile = File(...), password: str = Form("pdfmasry")):
    job_id, jdir, orig = await _save_upload_to_job(file)
    input_path = os.path.join(jdir, "input.bin")
    output_path = os.path.join(jdir, "unlocked.pdf")
    try:
        cmd = ["qpdf", f"--password={password}", "--decrypt", input_path, output_path]
        subprocess.run(cmd, check=True, capture_output=True)
        response_data = _make_response(job_id, output_path, f"unlocked_{orig}", "application/pdf")
        background_tasks.add_task(_delete_job_after_delay, job_id)
        return response_data
    except Exception:
        background_tasks.add_task(_delete_job_after_delay, job_id, delay_seconds=5)
        raise HTTPException(status_code=500, detail="فشل فك الحماية، قد تكون كلمة المرور خاطئة")


@app.post("/api/pdf-to-image")
async def pdf_to_image(background_tasks: BackgroundTasks, file: UploadFile = File(...)):
    job_id, jdir, orig = await _save_upload_to_job(file)
    input_path = os.path.join(jdir, "input.bin")
    pages_dir = os.path.join(jdir, "pages")
    os.makedirs(pages_dir, exist_ok=True)
    try:
        cmd = ["pdftoppm", "-jpeg", "-r", "150", input_path, os.path.join(pages_dir, "page")]
        subprocess.run(cmd, check=True, capture_output=True)

        zip_base = os.path.join(jdir, "pages_archive")
        shutil.make_archive(zip_base, "zip", pages_dir)
        zip_path = f"{zip_base}.zip"

        base = os.path.splitext(orig)[0] or "document"
        response_data = _make_response(job_id, zip_path, f"{base}_images.zip", "application/zip")
        background_tasks.add_task(_delete_job_after_delay, job_id)
        return response_data
    except Exception:
        background_tasks.add_task(_delete_job_after_delay, job_id, delay_seconds=5)
        raise HTTPException(status_code=500, detail="فشل تحويل الملف إلى صور")


@app.post("/api/word-to-pdf")
@app.post("/api/excel-to-pdf")
async def office_to_pdf(background_tasks: BackgroundTasks, file: UploadFile = File(...)):
    job_id, jdir, orig = await _save_upload_to_job(file)
    # LibreOffice needs the input to have a proper extension
    input_ext = os.path.splitext(orig)[1] or ".docx"
    input_path = os.path.join(jdir, f"input{input_ext}")
    canonical_input = os.path.join(jdir, "input.bin")
    shutil.move(canonical_input, input_path)

    try:
        cmd = ["libreoffice", "--headless", "--convert-to", "pdf", input_path, "--outdir", jdir]
        subprocess.run(cmd, check=True, capture_output=True)
        # LibreOffice writes <basename>.pdf where basename = os.path.splitext(input_filename)[0]
        libre_output = os.path.join(jdir, f"input.pdf")
        if not os.path.exists(libre_output):
            # Some versions name it after original — glob for any .pdf just in case
            candidates = [f for f in os.listdir(jdir) if f.lower().endswith(".pdf")]
            if candidates:
                libre_output = os.path.join(jdir, candidates[0])
            else:
                raise RuntimeError("LibreOffice produced no PDF")

        base = os.path.splitext(orig)[0] or "document"
        response_data = _make_response(job_id, libre_output, f"{base}.pdf", "application/pdf")
        background_tasks.add_task(_delete_job_after_delay, job_id)
        return response_data
    except Exception:
        background_tasks.add_task(_delete_job_after_delay, job_id, delay_seconds=5)
        raise HTTPException(status_code=500, detail="فشل تحويل المستند إلى PDF")
